server:
  port: 19090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/jerry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
logging:
  level:
    com.zaxxer.hikari: INFO
    org.springframework.jdbc: INFO
wx:
  specialOpenIdList:
    - oWrc7vn8C0n6YNs7jF8VRH4AthfE

siliconflow:
  accessKeyID: 'sk-ikbkcokceleimnjbszkftvijplkwhsheztwytamieuvigjrt'
  chatCompletionUrl: 'https://api.siliconflow.cn/v1/chat/completions'
  model: 'deepseek-ai/DeepSeek-V3'

aliyun:
  oss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    bucket-name: "wx-pusher"
